### ISSUE TITLE
Following indented link is not working

### ISSUE THREAD

**Issue by ashincoder** [nvim-neorg/neorg#196] opened 2021-11-18 11:01 UTC
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using either 0.5 stable or the latest compiled 0.6 version

### Neovim Version

NVIM v0.5.1 Build type: Release LuaJIT 2.0.5

### Log Output

Not required for this issue

### Branch

unstable

### Loaded modules

```lua 
      ["core.defaults"] = {},
      ["core.highlights"] = {},
      ["core.integrations.telescope"] = {},
      ["core.norg.concealer"] = {
         config = {
            icon_preset = "diamond",
            dim_code_blocks = true,
         },
      },
      ["core.norg.esupports"] = {},
      ["core.presenter"] = {
         config = {
            zen_mode = "zen-mode",
         },
      },
      ["core.norg.dirman"] = {
         config = {
            workspaces = {
               my_workspace = "~/Neorg",
               my_notes = "~/Neorg/notes",
               gtd = "~/Neorg/gtd",
            },
         },
      },
      ["core.gtd.base"] = {
         config = {
            workspace = "gtd",
         },
      },
      ["core.integrations.treesitter"] = {
         config = {
            highlights = {
               Heading = {
                  ["1"] = {
                     Title = "+TSTitle",
                     Prefix = "+TSTitle",
                  },
               },
               Quote = {
                  ["1"] = {
                     [""] = "+Grey",
                     Content = "+Grey",
                  },
               },
            },
         },
      },
      ["core.norg.completion"] = {
         config = {
            engine = "nvim-cmp",
         },
      },
      ["core.keybinds"] = {
         config = {
            default_keybinds = true,
            neorg_leader = "<Leader>o",
         },
      },
   },
```

### Expected behavior

When I add a link to a file, wheather the link format is indented or not it should go to the specified link.

### Actual behavior

When the link is indented, opening the link to a file won't work withing neorg. But if the link is not indented it works. I have linked the behaviour in the asciinema rec given below.

### Potentially conflicting plugins

I can hardly think of one. Maybe treesitter. No idea.

### Other information

[![asciicast](https://asciinema.org/a/IWnBTcBpO5936tr5FPUe67OGv.svg)](https://asciinema.org/a/IWnBTcBpO5936tr5FPUe67OGv)

### Help

No

**Comment by mrossinek** [comment] 2021-11-18 12:11
We are currently completely overhauling the syntax for links in Neorg, see #160, #178 and nvim-neorg/tree-sitter-norg#14.
Therefore, we will likely not be fixing this issue as such but instead ensure that this behavior is working as expected with the new link format.

I'm going to assign this to @vhyrro who is mostly working on this refactoring.

**Comment by mrossinek** [comment] 2021-12-13 23:06
@ashincoder Could you please check whether you are still running into this issue after updating to the latest neorg on the `main` branch + running `:TSUpdate norg`? If yes, please provide a minimal reproducible example

**Comment by ashincoder** [comment] 2021-12-14 04:04
The treesitter is acting weird and buggy. When making a link the letters inside it are changing. Is it a concealer issue or smthng ?
Also the neorg-telescope may have to updated according to the new syntax changes. The link inserted are in the deprecated way.

https://user-images.githubusercontent.com/83629316/145931049-82c09169-45fa-4ad3-b13b-f01e85741f77.mp4

The issue is solved though. Indented link are followed.

**Comment by mrossinek** [comment] 2021-12-14 07:09
Yes the slightly awkward behavior is due to concealing. I hope to improve that in the upcoming weeks.

The telescope update is almost ready, see also: https://github.com/nvim-neorg/neorg-telescope/pull/6

And finally: your link is formatted incorrectly. You want `{:2021/12/14:* Maths}`.
Notice the space is _after_ the `*` icons (not in front).

**Comment by ashincoder** [comment] 2021-12-14 08:29
Ok, thank you for the clarification. Also looking forward for a great outcome. :smile:

**Comment by mrossinek** [comment] 2021-12-14 17:36
> Ok, thank you for the clarification. Also looking forward for a great outcome. smile

Can this be closed then?

**Comment by ashincoder** [comment] 2021-12-15 00:13
Yeah sure

**Closed** 2021-12-15 07:00 UTC
Labels: bug, existing modules
