### ISSUE TITLE
Code blocks have strange background color

### ISSUE THREAD

**Issue by xbladesub** [nvim-neorg/neorg#991] opened 2023-07-16 19:18 UTC
<img width="1195" alt="image" src="https://github.com/nvim-neorg/neorg/assets/45129790/750dc0a4-eb87-4262-83f9-d7573bde17b4">

Is it something that I can change in neorg's settings or it's related to something else?
I use neovide + neovim 0.9

**Comment by max397574** [comment] 2023-07-17 05:27
that's intended behavior
it doesn't look that ugly if you don't have a transparent background
you can disable that in the concealer config
don't know the exact table keys rn though

**Comment by vhyrro** [comment] 2023-08-07 13:59
As max said this is a default behaviour of the concealer. You can check out the snippet that disables it [here](https://github.com/nvim-neorg/neorg/wiki/Concealer#configuration-for-iconsthis-table-contains-the-full-configuration-set-for-each-icon-includingits-query-where-to-be-placed-render-functions-how-to-be-placed-andcharacters-to-usefor-most-use-cases-the-only-values-that-you-should-be-changing-is-the-iconicons-fieldicon-is-a-string-while-icons-is-a-table-of-strings-for-multilevel-elements-likeheadings-lists-and-quotesto-disable-part-of-the-config-replace-the-table-with-false-or-prepend-false-and-to-itfor-example-done--false-or-done--false-and---)! Set the `code_block` variable to `false` to disable :)

Closing the issue!

**Closed by vhyrro** 2023-08-07 13:59 UTC
