### ISSUE TITLE
Foldtext bugged

### ISSUE THREAD

**Issue by jghauser** [nvim-neorg/neorg#499] opened 2022-07-04 19:57 UTC
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.2

### Neorg setup

require("neorg").setup({
	load = {
		["core.defaults"] = {}, -- Load all the default modules
		["core.norg.concealer"] = {}, -- Allows for use of icons
	},
})

### Actual behavior

When opening a fold, writing some text and then closing it, sometimes the foldtext becomes garbled.
![20220704_21h50m36s_grim](https://user-images.githubusercontent.com/10319377/177211051-53767424-d243-44f5-b802-f61b3f3517b6.jpeg)

### Expected behavior

Fold text displays normally

### Steps to reproduce

Create a file with folds, open them, add some text in the section, and close the fold again. It doesn't always happen, and I'm not quite sure what triggers it.

### Other information

I think it's an issue with the concealer as the problem doesn't show up when I disable that module.

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by vhyrro** [comment] 2022-07-08 15:31
Hey! This issue was caused by the concealer leaving leftover extmarks in certain scenarios (sometimes even triple the amount of necessary extmarks 👀). Because of this the foldtext algorithm broke in very weird ways when it received duplicates lol

Let me know if it's fixed on your end!

**Closed** 2022-07-08 15:42 UTC
Labels: bug
