### ISSUE TITLE
Wiki(User Keybinds): Broken Link

### ISSUE THREAD

**Issue by grtcdr** [nvim-neorg/neorg#382] opened 2022-02-25 01:12 UTC
Hi, I was browsing through the wiki (it's very well organized, by the way -- so, good job on that!) and stumbled upon a broken link, just thought I'd let you know since the wiki isn't editable by the public.

The `core.keybinds.keybinds` link in [this wiki page](https://github.com/nvim-neorg/neorg/wiki/User-Keybinds#imports) should point to [this file](https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/keybinds/keybinds.lua), rather than [this](https://github.com/nvim-neorg/neorg/tree/unstable/lua/neorg/modules/core/keybinds/keybinds.lua), as the `unstable` branch no longer exists.

**Comment by danymat** [comment] 2022-02-27 15:57
Hello ! This is a duplicate of #327. I'm trying to make them work again, I will tell you when it's fixed. Thanks for the feedback

**Comment by danymat** [comment] 2022-02-27 17:17
Hello ! this issue should now be fixed !

**Closed** 2022-02-27 17:17 UTC
Labels: bug, documentation

**Comment by grtcdr** [comment] 2022-02-27 18:41
Thank you so much, I apologize for reporting a duplicate.
