### ISSUE TITLE
Otter integration breaks on alternate filetypes

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorg/neorg#1488] opened 2024-06-26 17:40 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.10.0

### Neorg setup

N/A

### Actual behavior

Neorg seems to break whenever otter integration is activated and one tries to edit a file with an alternate filetype.

### Expected behavior

No error.

### Steps to reproduce

- Enter a `.norg` file
- Activate otter integration
- (optional) disable otter integration
- Move to a separate file

### Other information

(cc @benlubas, you're likely to know what the root cause of this issue is much faster than I am :p)

Below is the error log. It doesn't point to any individual Neorg path, but the error only triggers once the otter integration itself is activated.
```
Error detected while processing DiagnosticChanged Autocommands for "*":
Error executing lua callback: ...rro/.local/share/nvim/rocks/rocks_rtp/lua/otter/init.lua:184: attempt to index a nil value
stack traceback:
        ...rro/.local/share/nvim/rocks/rocks_rtp/lua/otter/init.lua:184: in function <...rro/.local/share/nvim/rocks/rocks_rtp/lua/otter/init.lua:183>
        [C]: in function 'nvim_exec_autocmds'
        ...0/nvim-linux64/share/nvim/runtime/lua/vim/diagnostic.lua:1033: in function 'set'
        ...im-linux64/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:260: in function 'handle_diagnostics'
        ...im-linux64/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:293: in function 'handler'
        ...0/nvim-linux64/share/nvim/runtime/lua/vim/lsp/client.lua:1005: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Help

None

**Comment by benlubas** [comment] 2024-06-26 20:30
I'm having trouble with otter not even updating diagnostics anymore. I'll add this to the list of things to look into

**Comment by benlubas** [comment] 2024-06-28 22:34
Can confirm that this also breaks with markdown files and is most likely a bug in otter.nvim

**Comment by benlubas** [comment] 2024-08-15 03:22
think this was fixed by https://github.com/jmbuhr/otter.nvim/issues/161

either way, can't reproduce it anymore

**Closed by benlubas** 2024-08-15 03:22 UTC
Labels: bug
