### ISSUE TITLE
Treesitter Integration Not Working

### ISSUE THREAD

**Issue by johnallen3d** [nvim-neorg/neorg#19] opened 2021-07-14 15:14 UTC
I can't put my finger on what I'm missing but I can't seem to get my `@code` blocks to be formatted.

<img width="433" alt="CleanShot 2021-07-14 at 10 56 26@2x" src="https://user-images.githubusercontent.com/184915/125644409-016ed87c-68f9-4d03-aa18-301dd9c4557e.png">

I believe I've followed the instructions:

```lua
require('neorg').setup {
  load = {
    ['core.defaults'] = {},
    ['core.norg.concealer'] = {},
  }
}

local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()

parser_configs.norg = {
    install_info = {
        url = "https://github.com/vhyrro/tree-sitter-norg",
        files = { "src/parser.c" },
        branch = "main"
    },
}

require('nvim-treesitter.configs').setup {
  ...
```

I've confirmed that I have the Ruby Treesitter parser installed (I've also tried JavaScript).

<img width="946" alt="CleanShot 2021-07-14 at 11 04 13@2x" src="https://user-images.githubusercontent.com/184915/125645395-374704de-15ce-42be-a58e-7edbf1838e5d.png">

I've tried the `unstable` branch as well in case that mattered.

---

side question -- is there any way to influence the size or color of the glyphs? I've tried a couple of different colorschemes but the glyphs end up a little hard to see (note: I've scaled up the font size in my screenshots here).

**Comment by vhyrro** [comment] 2021-07-14 15:42
Hm, that's particularly odd. You did run `:TSUpdate` to install the norg parser itself too, right? Just wanna make sure :P

If you could, try using this config:
```lua
require('neorg').setup {

	load = {
		["core.defaults"] = {},
		["core.norg.concealer"] = {},
	},

	-- Set custom logger settings
	logger = {
		level = "trace"
	},

}
```

Then run `:echo stdpath('data')`. In the directory that was printed there should be a `neorg.log`. Delete that, then reenter a .norg file. Paste the content of `neorg.log` here so I can take a deeper look at what's happening please.

As for the glyphs there is no way I know of to simply change their size (because of TUI limitations). The colour is not changeable either because we're currently using conceals, meaning that every icon is bound to a single highlight group: `Conceal`. If you were to change the `Conceal` highlight you'd affect every other icon's colour too. I am currently working on an implementation that uses a technique I learned from @akinsho which will use extmarks instead of conceals. When I manage to successfully implement that you'll be able to change the colours of individual icons with no problem :)

**Comment by vhyrro** [comment] 2021-07-14 15:44
Ah, I think I may have found the problem actually.
Does anything change if you run neorg's setup function *after* nvim-treesitter's setup function? It seems that neorg gets set up too early and the highlights etc. simply don't get registered

**Comment by johnallen3d** [comment] 2021-07-14 17:06
Thanks for the quick response @vhyrro! Your first question (re: `TSUpdate`) put me on the right track. I had done everything besides adding `norg` to the list of `ensure_installed` for Treesitter. 🤦‍♂️ I added it there, re-opened a `.norg` file and 💥! Perhaps it's just me, but you might consider adding a note to the README or Wiki about this?

Very happy to hear that there's a chance we'll be able to imact the glyphys in the future! For now maybe I'll tweak my existing `Conceal` highlight group.

Thanks again for the help!

**Comment by johnallen3d** [comment] 2021-07-14 17:07
FWIW - calling `setup` for norg before or after Treesitter both work.

**Comment by vhyrro** [comment] 2021-07-14 17:09
Awesome! I'll create a note about `ensure_installed` in the README when I get the time :)

**Comment by vod3** [comment] 2021-07-15 16:28
hi there, I'm in the same boat.
My codeblock ist formated, but all the norg stuff is without color.
![150721-182600](https://user-images.githubusercontent.com/22642893/125823428-31b9c6dd-6761-447d-b129-2e3d5e4904be.png)


I have the norg setting in the ensured_installed list and did a :TSUpdate, but it wont work I'm afraid, even after :e as you suggested.
Any Ideas?
Thanks!

**Comment by vhyrro** [comment] 2021-07-15 16:44
The usual issue for highlights not working is the loading of Neorg (and therefore its parser) before nvim-treesitter is active.
`nvim-treesitter` needs to be loaded for the highlights to be enabled. I recall having this problem. You can try verifying this by running:
```vim
:hi Neorg
```
and then tab completing through the options. If they're not present or they're all set to `cleared` then you know it's a loading order issue. Make sure that treesitter loads before neorg does.
Something that can also impact highlights not working is lazy loading Neorg with `ft`. Yeah, I know, I wrote in the README that you can do that, I'm planning on removing it. Lazy loading causes highlights to not work for some reason :(

**Comment by vod3** [comment] 2021-07-15 16:51
Thank you, it was a loading order issue. opening a .norg file from the terminal doesn't work with hightlights, but opening neovim first and then opening the file inside neovim is working.

any idea how to get treesitter to load first before neorg?

Thanks and good luck with your project, love the idea!

**Comment by vhyrro** [comment] 2021-07-15 16:55
Thank you! There's a few ways, it depends on your configuration. If you're using packer:
```lua
use {
    'vhyrro/neorg',
    after = "nvim-treesitter", -- Ensures that neorg loads after nvim-treesitter
    config = ...,
}
```

If you're dealing with a different plugin manager (or a different configuration style in general) you probably want to make sure that neorg's `setup()` gets invoked _after_ `nvim-treesitter.configs`'s setup() function.

**Comment by vod3** [comment] 2021-07-15 16:59
Treesitter is one of the first things I load, and neorg is at the very bottom of my init.lua. I use Paq btw.
Is there any other possibility?

**Comment by vhyrro** [comment] 2021-07-15 17:29
Hm, I don't know in that case. You would have to toy around a bit and see whether anything sticks. I wish I could fix it or be able to diagnose the problem right away, but loading orders and stuff like that are completely out of my control.

**Comment by vod3** [comment] 2021-07-15 17:42
it's interesting that all my other files get highlights without problems. Even in the telescope previewer, all filetypes look good, only norg is without syntax highlights. I will update you with new insights if I find a solution.

**Comment by vhyrro** [comment] 2021-07-15 17:58
The reason is because most of your filetypes are natively supported by `nvim-treesitter`. Neorg is not, and it uses its own custom queries defined in the `queries/norg` directory of the plugin.

**Comment by vhyrro** [comment] 2021-07-15 18:01
Let me try something real quick, I'll put the queries in `after/queries/norg` instead of just `queries/norg`. I hope that that will delay the queries a bit more and make them load more consistently. Gimme a minute

**Comment by vhyrro** [comment] 2021-07-15 18:05
Alright, @vod3 please try updating the plugin now. Ensure once more (juuust in case :P) that the order of plugin initialization is correct and reenter a .norg file. Let me know whether anything fixed itself or if we're still dealing with the same problem.

**Comment by vod3** [comment] 2021-07-15 18:31
Unfortunately, it did't work. Maybe you can spot an error on my side, here is my init.lua (its currently all in one file)
https://pastebin.com/3EY5fP5f

**Comment by vhyrro** [comment] 2021-07-15 20:03
Hey, so I installed your configuration to do some playing around and have gotten it to work. Is it a bit hacky? Yeah it is.

The issue is loading order. I have no idea why (I will look into this) but the neorg simply loads too quickly for treesitter to catch up.
The way I fixed this is by creating an `after/ftplugin/norg.lua` file and putting the Neorg configuration there, that way the config will only run whenever a .norg file is opened. I see that you have a one-file config and so adding extra files might not be your style but it's the only way I've managed to get it to work. Another method is by creating an autocommand to trigger on .norg files but at that point it's just hacks to get stuff to work (which nobody likes).

**Comment by vod3** [comment] 2021-07-15 20:13
I can live with that, I simply will open the .norg file from within neovim, thanks for your time.
I'm very interested in how your project will evolve, good luck!

**Comment by vhyrro** [comment] 2021-07-17 16:47
Just commenting again to say that the README now has more info regarding treesitter issues. I'll close this down until someone's treesitter doesn't work despite trying all the steps mentioned there.

**Comment by zmheiko** [comment] 2021-10-08 17:17
Thanks @vhyrro, your guess was spot on. While I checked that I was running the latest TreeSitter, I was actually running an old version of Neorg *facepalm. It is working as expected now.

Regarding @jonasstr's issue. I only noticed because I forgot to enable highlighting at some point myself. Maybe one more sentence in the readme that points out that highlighting must be enabled in the TreeSitter config would be a good idea. Maybe even adding the corresponding line to the existing example config:
```
require('nvim-treesitter.configs').setup {
	ensure_installed = { "norg", "haskell", "cpp", "c", "javascript", "markdown" },
	highlight = {enable = true},
}
```
Some people might install TreeSitter for the first time while setting up Neorg and therefore might not read the nvim-treesitter readme carefully enough.

**Comment by zmheiko** [comment] 2021-10-08 17:20
Cool. Thanks for your great work and support!

**Closed** 2021-10-08 17:56 UTC
Labels: Category::Parser

**Comment by hathawayANdRX105** [comment] 2022-03-18 09:08
I also occur this problem , and I did set `ensure_installed ` and `highlight ` in nvim-treesitter config which installed norg , 
also set `after = "nvim-treesitter"` in my packer's setup function . 
just  like :

> 
	use {
	    "nvim-neorg/neorg",
	    after = "nvim-treesitter",
	}
> 
but I reopen my nvim to find out nothing change which was still no hightlight , whilst hightlight settings was founded when I typed `:hightlight Neorg` . Eventually , I make sure the loading order of treesitter happen before neorg. Adding that fixs the hightlight problem. Would you add some reminding in READ.md ?

> use {  'nvim-treesitter/nvim-treesitter', before='neorg', run = ':TSUpdate' }

**Comment by vhyrro** [comment] 2022-03-18 12:13
Thanks for the heads up! I'll include that in the README then :)

**Comment by hathawayANdRX105** [comment] 2022-03-19 07:04
Sorry!!! I check out the config of `paker.use()` , the `before` attribute seems to be unuseful in function of the `use`. 
> 	use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
> 	use { "nvim-neorg/neorg", after='nvim-treesitter'}

And I found that when first opening nvim just run `:NeorgStart` , using the plugin of 'impatient' and looking at `LuaCacheLog`, it centainly load up those config of neorg from `$env:LOCALAPPDATA\nvim-data\site\pack\packer\opt\neorg\..`, but the highlights of norg file were not in place.
I try to run `:PackerLoad neorg` and then `:NeorgStart` , that comes out the highlights everytimes. Sorry for my poor english and  I apologize for last  careless comment wasting you time.  '^'

**Comment by vhyrro** [comment] 2022-03-19 08:04
It's fine! Mistakes happen :)

When i get the time I'll reupdate the readme again, no worries
