### ISSUE TITLE
Failed to run `config` for neorg - `/usr/share/nvim/runtime/lua/vim/re.lua:150: attempt to perform arithmetic on local 'item' (a userdata value)`

### ISSUE THREAD

**Issue by xfzv** [nvim-neorg/neorg#1516] opened 2024-07-16 11:46 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.11.0-dev-434+ga0fd51c1e-dirty

### Neorg setup

```lua
return {
  "nvim-neorg/neorg",
  cmd = "Neorg",
  ft = "norg",
  config = function()
    require("neorg").setup({
      load = {
        ["core.completion"] = {
          config = {
            engine = "nvim-cmp",
          },
        },
        ["core.concealer"] = {
          config = {
            icons = {
              code_block = {
                conceal = true, -- If `true`, will conceal (hide) the `@code` and `@end` portion of the code block
                content_only = true, -- If `true`, will only dim the content of the code block (without the `@code` and `@end` lines)
              },
            },
            icon_preset = "diamond",
          },
        },
        ["core.defaults"] = {},
        ["core.export"] = {},
      },
    })
  end,
}
```

### Actual behavior

After updating Neovim (Git) to https://github.com/neovim/neovim/commit/a0fd51c1e2db17ab21e2a2c907b232d05dfffc88, the following is printed when opening a `norg` file:

```console
Failed to run `config` for neorg

/usr/share/nvim/runtime/lua/vim/re.lua:150: attempt to perform arithmetic on local 'item' (a userdata value)

# stacktrace:
  - /usr/share/nvim/runtime/lua/vim/re.lua:150
  - vim/_init_packages.lua:0 _in_ **__index**
  - /neorg/lua/neorg/modules/core/tempus/module.lua:18
  - /neorg/lua/neorg/core/modules.lua:442 _in_ **load_module**
  - /neorg/lua/neorg/core/modules.lua:206 _in_ **load**
  - /neorg/lua/neorg/core/modules.lua:405 _in_ **load_module**
  - /neorg/lua/neorg/init.lua:100 _in_ **org_file_entered**
  - /neorg/lua/neorg/init.lua:45 _in_ **setup**
  - ~/.config/nvim/lua/plugins/neorg.lua:6 _in_ **config**
  - /usr/share/nvim/runtime/filetype.lua:36
  - vim/shared.lua:0
  - /usr/share/nvim/runtime/filetype.lua:35
```

Plus,

```lua
icon_preset = "diamond",
```

isn't working anymore.

It used to work just fine yesterday so I guess this is due to a recent Neovim commit (2024-07-16).

### Expected behavior

No error is printed

### Steps to reproduce

1. Update Neovim to https://github.com/neovim/neovim/commit/a0fd51c1e2db17ab21e2a2c907b232d05dfffc88
2. Open a `.norg` file with the setup above
3. The error is printed

### Help

None

**Comment by benlubas** [comment] 2024-07-16 22:15
does this happen on stable? nvim v0.10?

**Comment by benlubas** [comment] 2024-07-16 22:17
`icon_preset = "diamond"` is working perfectly fine for me. Could you elaborate on what you mean by "isn't working"

**Comment by Reyu** [comment] 2024-07-17 00:34
I'm having the same issue. I just upgraded to the latest tag, and now I get an error every time NeoVim loads.
```
Failed to run `config` for neorg
/usr/share/nvim/runtime/lua/vim/re.lua:150: attempt to perform arithmetic on local 'item' (a userdata value)
# stacktrace:
  - /usr/share/nvim/runtime/lua/vim/re.lua:150
  - vim/_init_packages.lua:0 _in_ **__index**
  - /neorg/lua/neorg/modules/core/tempus/module.lua:18
  - /neorg/lua/neorg/core/modules.lua:442 _in_ **load_module**
  - /neorg/lua/neorg/core/modules.lua:337 _in_ **load_module**
  - /neorg/lua/neorg/core/modules.lua:337 _in_ **load_module**
  - /neorg/lua/neorg/init.lua:100 _in_ **org_file_entered**
  - /neorg/lua/neorg/init.lua:45 _in_ **setup**
  - ~/.config/neorg/init.lua:46 _in_ **config**
  - ~/.config/neorg/init.lua:23
```
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```
I found the minimum config to trigger it is just loading `core.ui.calendar`. With just that submodule in the kickstart config, I get the error.

**Comment by vhyrro** [comment] 2024-07-17 08:59
The actual source of this issue stems from the Neovim source from what I can tell. In Neorg's code we only compile a single pattern, nothing remotely complex or hacky. I'll have to debug this further.

**Comment by benlubas** [comment] 2024-07-17 11:29
@vhyrro unless you're seeing this, it seems it's a problem with the version of luajit that their neovim is complied with.

`LuaJIT 2.1.0-beta3` vs. `2.1.1713484068`

**Comment by benlubas** [comment] 2024-07-17 11:29
@Reyu that's a different problem that was already fixed

**Comment by Reyu** [comment] 2024-07-17 14:54
> @Reyu that's a different problem that was already fixed

@benlubas I'll open a a separate issue if it is not the same, but I can assure you that it's not fixed. Latest stable Neovim and Neorg is giving me this error.

**Comment by benlubas** [comment] 2024-07-17 14:56
@Reyu I'm not sure what I read earlier, that does look like the same issue, my bad.

**Comment by Reyu** [comment] 2024-07-17 15:00
@benlubas No worries, I've misread things at work only to start an uneeded fuss at work more times than I can count. Can hardly blame someone for similar in an open source project. Heh

I am on Gentoo, as well, if I can help try and diagnose anything. It seems to be a common factor, so far.

**Comment by benlubas** [comment] 2024-07-17 17:40
seems like Gentoo's nvim package is just broken then. My best guess is that it's shipping with the wrong version of lpeg somehow

**Comment by benlubas** [comment] 2024-07-17 17:43
You can actually go into `/usr/share/nvim/runtime/lua/vim/re.lua` and add a `vim.print(m)` to see if it looks right. Specifically make sure the `version` field is `"LPeg 1.1.0"`

**Comment by vhyrro** [comment] 2024-07-17 18:16
Oof, that potentially sounds like the reason. Since Neorg uses luarocks I guess we could require our own version of lpeg instead, but I'd rather try to fix this on Neovim's side (which is the root cause). Maybe Neovim should refuse to build with older versions of lpeg?

**Comment by Reyu** [comment] 2024-07-17 20:07
Came back to this after work, and after reading through everything I bumped the version of lpeg up in an overlay and reinstalled it.
With lpeg-1.1.0, there are no errors at startup, and I can actually use the calendar functions.
Need to get Gentoo to add the new version, but that's not a problem for here, I think.

**Comment by rob32** [comment] 2024-07-24 14:07
> I'm having the same issue. I just upgraded to the latest tag, and now I get an error every time NeoVim loads.
> 
> ```
> Failed to run `config` for neorg
> /usr/share/nvim/runtime/lua/vim/re.lua:150: attempt to perform arithmetic on local 'item' (a userdata value)
> # stacktrace:
>   - /usr/share/nvim/runtime/lua/vim/re.lua:150
>   - vim/_init_packages.lua:0 _in_ **__index**
>   - /neorg/lua/neorg/modules/core/tempus/module.lua:18
> ...

Same here on my fedora 40 system.

```
~ ❱ nvim -v
NVIM v0.10.0
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
```
Maybe it makes sense to take the calender out of `core.defaults` again (temporarily)?

**Comment by cryptomilk** [comment] 2024-07-24 14:16
> Same here on my fedora 40 system.

Will be fixed soon:

`koji wait-repo f40-build-side-92914 && fedpkg build --target=f40-build-side-92914`

Waiting ...

**Comment by cryptomilk** [comment] 2024-07-24 14:45
Fedora 40 Update: https://bodhi.fedoraproject.org/updates/FEDORA-2024-1b0f0b9cdc

**Comment by dmonad** [comment] 2024-07-26 09:45
This issue can be resolved by upgrading neovim to the latest stable release v0.10.1.

Quick fix for Fedora users who don't want to wait for the release:

```sh
# upgrade neovim from the testing repo
sudo dnf install neovim --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-1b0f0b9cdc
```

**Comment by dmonad** [comment] 2024-07-26 11:29
nightly is not officially supported by neorg. But if it works for you by upgrading `lpeg` that's good I guess.

On fedora, I'm now using `lua-lpeg 1.0.2-13.fc40` and `nvim v.10.1` and I don't encounter the issue anymore. 

```
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Comment by cryptomilk** [comment] 2024-07-26 11:34
The issue is not fixed by updating neovim to version 0.10.1, it is fixed by updating lua-lpeg to version 1.1.0.

https://bodhi.fedoraproject.org/updates/FEDORA-2024-1b0f0b9cdc includes lua-lpeg 1.1.0!

**Comment by dmonad** [comment] 2024-07-26 12:15
> The issue is not fixed by updating neovim to version 0.10.1, it is fixed by updating lua-lpeg to version 1.1.0.

Right, sorry. I used the wrong command to query the package version.. :sweat:

**Comment by JonasToth** [comment] 2024-08-13 19:23
I suffer from the same issue on Gentoo. The wiki suggests, that its possible to disable loading of specific modules: https://github.com/nvim-neorg/neorg/wiki/Defaults

It does not seem to work though. How could I mask `tempus` and `ui-calendar` for the time being without just deleting them from the `lua/modules/defaults/module.lua` file? (not nice for long term updates)

**Comment by max397574** [comment] 2024-08-13 20:16
Or just use bob ツ
https://github.com/MordechaiHadad/bob

**Closed** 2024-08-20 18:17 UTC
Labels: bug

**Comment by JonasToth** [comment] 2024-08-24 18:36
If anyone needs this on gentoo, here the version of my overlay https://github.com/JonasToth/jonas-overlay/tree/master/dev-lua/lpeg

(the previous source code location had certificate issues)

**Comment by JonasToth** [comment] 2024-08-31 11:09
Upstream gentoo should be fixed now. Can others please verify this too?
