### ISSUE TITLE
Concealer stopped working after upgrade to 8.0

### ISSUE THREAD

**Issue by michaeyk** [nvim-neorg/neorg#1417] opened 2024-05-08 18:20 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.5

### Neorg setup

```
require("neorg").setup {
    load = {
        ["core.defaults"] = {},
        ["core.dirman"] = {
            config = {
                workspaces = {
                    notes = "~/documents/notes",
                },
                default_workspace = "notes",
            }
        },
        -- ["core.tempus"] = {}, -- need nvim 10.0 or greater
            ["core.completion"] = { config = { engine = "nvim-cmp", name = "[Norg]" } },
        ["core.integrations.telescope"] = {},
        ["core.integrations.treesitter"] = {},
        ["core.concealer"] = {
            config = {
                folds = false,
                icon_preset = "diamond",
            }
        },
        ["core.summary"] = {},
        ["core.export"] = {},
        ["core.keybinds"] = {
            -- https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/keybinds/keybinds.lua
                config = {
                    default_keybinds = true,
                    neorg_leader = "<Leader>",
                },
        },
    },
}

-- These groups allow customization of the Neorg highlights
vim.api.nvim_set_hl(0, '@neorg.markup.bold.norg', { link = 'NeorgCustomBold'})
vim.api.nvim_set_hl(0, '@neorg.markup.italic.norg', { link = 'NeorgCustomItalic'})
vim.api.nvim_set_hl(0, '@neorg.markup.strikethrough.norg', { link = 'NeorgCustomStrikethrough'})
vim.api.nvim_set_hl(0, '@neorg.links.description.norg', { link = 'NeorgCustomLink'})

-- This autocommand allows for automatic concealing of Neorg files.
-- There is a plugin already that does that, but this is a failsafe.
vim.api.nvim_create_autocmd({"BufEnter", "BufWinEnter"}, {
        pattern = {"*.norg"},
        callback = function ()
        vim.opt.conceallevel = 2
        vim.opt.concealcursor = 'nc'
        end
        })
```

### Actual behavior

Conceal doesn't work for links.
![2024-05-08-121031_screenshot](https://github.com/nvim-neorg/neorg/assets/603916/1ae1f148-bb0e-4f9c-996f-754fd539349d)

### Expected behavior

Links should be hidden unless cursor is on them. Strikethrough doesn't work either. Lists work as expected.

### Steps to reproduce

Noticed the problem after a successful upgrade to 8.0.

### Potentially conflicting plugins

Not sure. I tried commenting out some of my plugins, no help.

### Other information

I tried nvim nightly. I set the conceallevel explicitly. I have changed colorschemes. 

### Help

None

**Comment by benlubas** [comment] 2024-05-10 20:49
@michaeyk does conceal work in other parts of neovim? For markdown/json for example?

This seems like a conceal problem rather than a concealer problem b/c headings are working (which are handled by the concealer).

I can't reproduce this at all btw.

**Comment by michaeyk** [comment] 2024-05-12 02:16
Conceal works fine on markdown files.

**Comment by michaeyk** [comment] 2024-05-12 02:50
*bold text* doesn't conceal. It seems like headings are the only things that work.

**Comment by benlubas** [comment] 2024-05-12 14:06
Headings and lists probably. They're the two that are done differently to the links/bold/italic/etc.

This is exactly what I would expect to happen if conceallevel isn't set properly, but that can't be the case if you've set it manually (I'd just quadruple check to be sure `:set conceallevel?` or `:lua print(vim.opt.conceallevel:get())` in the norg buffer to see its value).

If you could provide a minimal nvim config for reproducing that would be great. If I can't reproduce the issue I unfortunately can't offer much more help.

**Comment by benlubas** [comment] 2024-05-12 14:10
Wait.

Do you have treesitter highlighting enabled?

**Comment by benlubas** [comment] 2024-05-12 14:13
no you don't. That's the issue. Add this to your configuration (you already load this plugin, you just never configure it).

```lua
{
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  config = function()
    ---@diagnostic disable-next-line: missing-fields
    require("nvim-treesitter.configs").setup({
      highlight = {
        enable = true,
        additional_vim_regex_highlighing = { "typst" },
      },
      indent = {
        enable = true,
      },
    })
  end,
}
```

**Comment by michaeyk** [comment] 2024-05-12 15:39
Thank you! That was it.

**Comment by vhyrro** [comment] 2024-05-17 16:31
Closing as fixed, this will become even less of an issue once we stop relying on nvim-treesitter :)

**Closed by vhyrro** 2024-05-17 16:31 UTC
Labels: bug
