### ISSUE TITLE
error when creating new note

### ISSUE THREAD

**Issue by snomics** [nvim-neorg/neorg#933] opened 2023-06-06 21:48 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-463+g780ab11b9

### Neorg setup

```
require('neorg').setup {
  load = {
    ['core.defaults'] = {},
    ['core.ui.calendar'] = {},
    ['core.highlights'] = {},
    ['core.dirman'] = {
      config = {
        workspaces = {
          perso = '~/neorg/perso',
          pro = '~/neorg/pro'
        },
      }
    },
    ['core.concealer'] = {},
  }
}

```

### Actual behavior

Use of Create new note produces the following error : 

```
Error executing Lua callback: ...nvim/lazy/neorg/lua/neorg/modules/core/ui/text_popup.lua:17: attempt to index field 'windows' (a nil value)
stack traceback:
        ...nvim/lazy/neorg/lua/neorg/modules/core/ui/text_popup.lua:17: in function 'create_prompt'
        ...nvim/lazy/neorg/lua/neorg/modules/core/dirman/module.lua:512: in function 'on_event'
        ...ntoine/.local/share/nvim/lazy/neorg/lua/neorg/events.lua:149: in function 'broadcast_event'
        ...im/lazy/neorg/lua/neorg/modules/core/keybinds/module.lua:446: in function <...im/lazy/neorg/lua/neorg/modules/core/keybinds/module.lua:431>
        ...im/lazy/neorg/lua/neorg/modules/core/keybinds/module.lua:430: in function 'on_event'
        ...ntoine/.local/share/nvim/lazy/neorg/lua/neorg/events.lua:149: in function 'broadcast_event'
        ...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:289: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:196>
```

### Expected behavior

Open the create new note window

### Steps to reproduce

Try to create a new note

### Other information

Coming back to commit 3caca5ac209aa8098a355837b5c4696d16804e19 solves the problem.
Seems to be introduced in 593e9b2a0826dfb8068a02277f4a45db00573e9a

### Help

None

**Comment by Laaronhooper** [comment] 2023-06-07 00:36
Getting the same issue

```
Error executing Lua callback: ...nvim/lazy/neorg/lua/neorg/modules/core/ui/text_popup.lua:17: attempt to index field 'windows' (a nil value)                                                                
stack traceback:                                                                                                                                                                                            
        ...nvim/lazy/neorg/lua/neorg/modules/core/ui/text_popup.lua:17: in function 'create_prompt'                                                                                                         
        ...nvim/lazy/neorg/lua/neorg/modules/core/dirman/module.lua:512: in function 'on_event'                                                                                                             
        .../.local/share/nvim/lazy/neorg/lua/neorg/events.lua:149: in function 'broadcast_event'                                                                                                      
        ...im/lazy/neorg/lua/neorg/modules/core/keybinds/module.lua:446: in function <...im/lazy/neorg/lua/neorg/modules/core/keybinds/module.lua:431>                                                      
        ...im/lazy/neorg/lua/neorg/modules/core/keybinds/module.lua:430: in function 'on_event'                                                                                                             
        .../.local/share/nvim/lazy/neorg/lua/neorg/events.lua:149: in function 'broadcast_event'                                                                                                      
        ...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:289: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:196> 
```

Not an issue with local leader as the following command <LocalLeader>ta, <LocalLeader>li amongst others are all working...

**Comment by vhyrro** [comment] 2023-06-07 07:11
I think I see what the problem is already. I'll have to refactor a large portion of `core.ui` but it'll be worth it in the long run. Might take some time for me to fix this issue!

**Comment by vhyrro** [comment] 2023-06-07 13:57
Hey! This should be fixed now on the latest `main` branch. Works on my end at least :D

**Comment by vhyrro** [comment] 2023-06-07 16:45
Yep @jqfeld, you're right! I also fixed that in the latest latest commit. Should be good now, if you find any bugs then please reopen this issue :)

**Closed by vhyrro** 2023-06-07 16:45 UTC
Labels: bug
