### ISSUE TITLE
gdt view pages exits after 3-4 seconds,

### ISSUE THREAD

**Issue by hardfau18** [nvim-neorg/neorg#299] opened 2022-01-05 11:45 UTC
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+nightly Build type: Release LuaJIT 2.1.0-beta3 Compiled by root@38173e3b24b3

### Neorg setup

```
    "nvim-neorg/neorg",
    config = function()
        require('neorg').setup {
            -- Tell Neorg what modules to load
            load = {
                ["core.defaults"] = {}, -- Load all the default modules
                ["core.norg.concealer"] = {}, -- Allows for use of icons
                ["core.gtd.base"] = {},
                ["core.norg.completion"] = {
                        config = {
                                engine =  "nvim-cmp" -- We current support nvim-compe and nvim-cmp only
                        }
                },
                ["core.norg.dirman"] = { -- Manage your directories with Neorg
                    config = {
                        workspaces = {
                            my_workspace = "~/neorg"
                        }
                    }
                }
            },
        }
    end,
    requires = "nvim-lua/plenary.nvim"
 ```

### Actual behavior

gives this below error before opening any view page like project view and exits in 2-3 seconds 
```
E5108: Error executing lua .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_close'
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155: in function 'delete_window'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_delete'
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:252: in function 'destroy'
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:330: in function <...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:326>
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:22: in function 'invoke_key_in_selection'
        [string ":lua"]:1: in main chunk
Error detected while processing WinLeave Autocommands for "<buffer=7>":
E5108: Error executing lua .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_close'
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:155: in function 'delete_window'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_buf_delete'
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:252: in function 'destroy'
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:330: in function <...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:326>
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:22: in function 'invoke_key_in_selection'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:245: Vim:E95: Buffer with this name already exists
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:245: in function <.../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:221>
        .../packer/start/neorg/lua/neorg/modules/core/ui/module.lua:378: in function 'create_norg_buffer'
        ...start/neorg/lua/neorg/modules/core/gtd/ui/displayers.lua:518: in function 'display_projects'
        ...rg/lua/neorg/modules/core/gtd/ui/views_popup_helpers.lua:497: in function <...rg/lua/neorg/modules/core/gtd/ui/views_popup_helpers.lua:496>
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:340: in function <...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:326>
        ...tart/neorg/lua/neorg/modules/core/ui/selection_popup.lua:22: in function 'invoke_key_in_selection'
        [string ":lua"]:1: in main chunk
```

### Expected behavior

shouldn't close till q or esc is pressed

### Steps to reproduce

* initialize fresh workspace.
* `Neorg gtd views`
* select project views

### Other information

tried with separate docker instance with fresh nvim installation with only below config
```
local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()

parser_configs.norg = {
	install_info = {
		url = "https://github.com/nvim-neorg/tree-sitter-norg",
		files = { "src/parser.c", "src/scanner.cc" },
		branch = "main",
	},
}

parser_configs.norg_meta = {
	install_info = {
		url = "https://github.com/nvim-neorg/tree-sitter-norg-meta",
		files = { "src/parser.c" },
		branch = "main",
	},
}

parser_configs.norg_table = {
	install_info = {
		url = "https://github.com/nvim-neorg/tree-sitter-norg-table",
		files = { "src/parser.c" },
		branch = "main",
	},
}

require("nvim-treesitter.configs").setup({
	-- One of "all", "maintained" (parsers with maintainers), or a list of languages
	ensure_installed = { "norg", "norg_meta", "norg_table" },

	-- Install languages synchronously (only applied to `ensure_installed`)
	sync_install = false,

	highlight = {
		enable = true,

		additional_vim_regex_highlighting = false,
	},
})
require("packer").startup(function()
	use({
		"hrsh7th/nvim-cmp",
		config = function()
			--------------------------
			local cmp = require("cmp")

			cmp.setup({
				mapping = {
					["<C-b>"] = cmp.mapping(cmp.mapping.scroll_docs(-4), { "i", "c" }),
					["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(4), { "i", "c" }),
					["<C-Space>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
					["<C-y>"] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
					["<C-e>"] = cmp.mapping({
						i = cmp.mapping.abort(),
						c = cmp.mapping.close(),
					}),
					["<CR>"] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
				},
				sources = cmp.config.sources({
					{ name = "neorg" }, -- For vsnip users.
				}, {
					{ name = "buffer" },
				}),
			})

			-- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
			cmp.setup.cmdline("/", {
				sources = {
					{ name = "buffer" },
				},
			})
		end,
	})
	--------------------------
	use("wbthomason/packer.nvim")
	use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
	use({

		"nvim-neorg/neorg",
		config = function()
			require("neorg").setup({
				-- Tell Neorg what modules to load
				load = {
					["core.defaults"] = {}, -- Load all the default modules
					["core.norg.concealer"] = {}, -- Allows for use of icons
					["core.gtd.base"] = {},
					["core.norg.completion"] = {
						config = {
							engine = "nvim-cmp", -- We current support nvim-compe and nvim-cmp only
						},
					},
					["core.norg.dirman"] = { -- Manage your directories with Neorg
						config = {
							workspaces = {
								my_workspace = "~/neorg",
							},
						},
					},
				},
			})
		end,
		requires = "nvim-lua/plenary.nvim",
	})
end)

```

These modules are enabled
```
core.autocommands
core.keybinds
core.integrations.treesitter
core.storage
core.neorgcmd.commands.module.load
core.gtd.ui.views_popup_helpers
core.neorgcmd
core.mode
core.gtd.queries.modifiers
core.gtd.ui.displayers
core.integrations.nvim-cmp
core.gtd.ui
core.gtd.queries
core.gtd.queries.retrievers
core.keybinds.default_keybinds
core.norg.concealer.preset_diamond
core.gtd.ui.edit_popup_helpers
core.norg.manoeuvre
core.norg.completion
core.ui
core.norg.concealer
core.scanner
core.norg.esupports
core.norg.qol.todo_items
core.gtd.queries.helpers
core.ui.text_popup
core.norg.esupports.metagen
core.norg.esupports.hop
core.highlights
core.norg.news
core.neorgcmd.commands.return
core.queries.native
core.norg.concealer.preset_brave
core.gtd.queries.creators
core.defaults
core.gtd.ui.selection_popups
core.gtd.base
core.neorgcmd.commands.module.list
core.norg.concealer.preset_basic
core.norg.concealer.preset_varied
core.norg.dirman
core.ui.selection_popup
core.norg.concealer.preset_safe
```

### Help

No

**Comment by danymat** [comment] 2022-01-05 12:04
Hello @hardfau18, it seems like the latest Neovim version has some breaking changes..
Can you try again with this fix ?

**Comment by hardfau18** [comment] 2022-01-05 12:37
now i am getting below error
```
[neorg] [ERROR 18:01:14] ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:513: Unable to create custom conceal for highlight: NeorgHeading1 - end_row value outside
range
```
i tried to use neovim provided by arch repo but same results,
version i tired 
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```

**Comment by danymat** [comment] 2022-01-05 12:41
Hmm, this seems to be a concealer issue, I will reference in a new issue. Is the first issue fixed btw ?

**Comment by danymat** [comment] 2022-01-05 12:46
So to be clear, this issue is now fixed ? (Sorry for my misunderstanding, I'm not native English fluent)

**Comment by hardfau18** [comment] 2022-01-05 12:49
not yet, the issue i am facing is when I open gtd project view, after 2-3 seconds it closes with the above error now

**Comment by danymat** [comment] 2022-01-05 13:01
Okay I can reproduce the issue. I'm trying to fix it rn

**Comment by helmecke** [comment] 2022-01-05 14:01
It now works for me. Thank you!

**Closed** 2022-01-05 14:05 UTC
Labels: bug
