### ISSUE TITLE
Neorg return quits Neovide completely

### ISSUE THREAD

**Issue by SpacewaIker** [nvim-neorg/neorg#959] opened 2023-06-23 15:11 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

0.9.1

### Neorg setup

    config = function()
      require("neorg").setup {
        load = {
          ["core.defaults"] = {}, -- Loads default behaviour
          ["core.concealer"] = {
            config = {
              icon_preset = "basic",
            },
          }, -- Adds pretty icons to your documents
          ["core.dirman"] = { -- Manages Neorg workspaces
            config = {
              workspaces = {
                notes = "~/notes",
              },
            },
          },
          ["core.summary"] = {},
        },
      }
    end,

### Actual behavior

When using the `Neorg return` command, the entire window closes (neovim quits).

### Expected behavior

The buffers containing `norg` files should close, returning the user to their other files.

### Steps to reproduce

1. Open Neovide
2. `Neorg workspace ....`
3. `Neorg return`

### Other information

As mentioned, this happens when using [Neovide](https://github.com/neovide/neovide). When using neovim in a terminal, this does not happen. This also does not happen when using `nvim-qt`.

### Help

None

**Comment by vhyrro** [comment] 2023-08-07 14:14
Hm, I've just tested it out and everything seems fine on my end with the latest Neovide! I even tried some more wacky things with splits and such and still no breakages. Maybe you're on an older version of Neovide?

**Comment by vhyrro** [comment] 2024-03-25 19:49
Tried this yet again but couldn't reproduce. Closing this :)

**Closed by vhyrro** 2024-03-25 19:49 UTC
Labels: bug
