### ISSUE TITLE
Incorrect concealer behavior on offset multi-paragraph definitions

### ISSUE THREAD

**Issue by SDPolukhin** [nvim-neorg/neorg#998] opened 2023-07-28 16:48 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.1

### Neorg setup

	load = {
		["core.defaults"] = {}, -- Loads default behaviour
		["core.concealer"] = {}, -- Adds pretty icons to your documents
		["core.dirman"] = { -- Manages Neorg workspaces
			config = {
				workspaces = {
					org = "~/Notes/org/",
					study = "~/Notes/study",
					life = "~/Notes/life/",
				},
				index = "index.norg",
			},
		},
	},

### Actual behavior

If a multi-paragraph definition has an offset and contains a list (either order or unordered), the "end of definition" symbol is displayed before the first element of the first list.
![incorrect_symbol](https://github.com/nvim-neorg/neorg/assets/73587278/70d5d3bf-78cf-41b4-94a9-242df31d1ee2)

### Expected behavior

The "end of definition" symbol should not be present before the list

### Steps to reproduce

Enter the following text into a .norg file and toggle the concealer on.

> \* Heading
> $$ definition
> \- Item
> \- Item 2

### Help

None

**Comment by champignoom** [comment] 2023-07-31 02:36
![image](https://github.com/nvim-neorg/neorg/assets/66909116/080b35e4-3ecf-4f3b-bad4-08f40f23749f)
This is likely a parser issue. A phantom definition suffix is automatically inserted at the beginning of the following line.

**Comment by vhyrro** [comment] 2023-07-31 06:19
"It's a feature, not a bug" lol. Treesitter inserts missing nodes when they are supposed to be there to not break the integrity of the AST and for better error recovery. These nodes are marked as "missing". @champignoom maybe the concealer should check whether `target_node:missing()` before concealing it? That is, don't conceal missing nodes :p

**Closed** 2023-08-01 10:07 UTC
Labels: bug
