### ISSUE TITLE
Concealer issue in GTD

### ISSUE THREAD

**Issue by hoaxdream** [nvim-neorg/neorg#383] opened 2022-02-25 08:52 UTC
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.6.1

### Neorg setup

```
local status_ok, neorg = pcall(require, "neorg")
if not status_ok then
    return
end

neorg.setup {
    load = {
        ["core.defaults"] = {},
        --["core.keybinds"] = {config = {default_keybinds = true, neorg_leader = '<Leader>o'}},
        ["core.gtd.base"] = {
            config = {
                workspace = "notes",
                projects = {
                    show_completed_projects = false,
                    show_projects_without_tasks = false,
                },
                custom_tag_completion = false,
            },
        },
        ["core.norg.completion"] = { config = { engine = "nvim-cmp" } },
        ["core.norg.concealer"] = {
            config = {
                icons = {
                    todo = {
                        enabled = true,

                        -- todo checkbox
                        done = {
                            enabled = true,
                            icon = "",
                            highlight = "NeorgTodoItemDoneMark",
                            query = "(todo_item_done) @icon",
                            extract = function() return 1 end,
                        },

                        pending = {
                            enabled = true,
                            icon = "",
                            highlight = "NeorgTodoItemPendingMark",
                            query = "(todo_item_pending) @icon",
                            extract = function() return 1 end,
                        },

                        undone = {
                            enabled = true,
                            icon = "×",
                            highlight = "NeorgTodoItemUndoneMark",
                            query = "(todo_item_undone) @icon",
                            extract = function() return 1 end,
                        },

                        uncertain = {
                            enabled = true,
                            icon = "",
                            highlight = "NeorgTodoItemUncertainMark",
                            query = "(todo_item_uncertain) @icon",
                            extract = function() return 1 end,
                        },

                        on_hold = {
                            enabled = true,
                            icon = "",
                            highlight = "NeorgTodoItemOnHoldMark",
                            query = "(todo_item_on_hold) @icon",
                            extract = function() return 1 end,
                        },

                        cancelled = {
                            enabled = true,
                            icon = "",
                            highlight = "NeorgTodoItemCancelledMark",
                            query = "(todo_item_cancelled) @icon",
                            extract = function() return 1 end,
                        },

                        urgent = {
                            enabled = true,
                            icon = "!",
                            highlight = "NeorgTodoItemUrgentMark",
                            query = "(todo_item_urgent) @icon",
                            extract = function() return 1 end,
                        }
                    },

                    -- todo list icon
                    list = {
                        enabled = true,

                        level_1 = {
                            enabled = true,
                            icon = "✦",
                            highlight = "NeorgUnorderedList1",
                            query = "(unordered_list1_prefix) @icon",
                        },

                        level_2 = {
                            enabled = true,
                            icon = " ❂",
                            highlight = "NeorgUnorderedList2",
                            query = "(unordered_list2_prefix) @icon",
                        },

                        level_3 = {
                            enabled = true,
                            icon = "  ✸",
                            highlight = "NeorgUnorderedList3",
                            query = "(unordered_list3_prefix) @icon",
                        },

                        level_4 = {
                            enabled = true,
                            icon = "   ★",  -- ○ ★ ⚝ ○ ◉ ★
                            highlight = "NeorgUnorderedList4",
                            query = "(unordered_list4_prefix) @icon",
                        },

                        level_5 = {
                            enabled = true,
                            icon = "•",
                            highlight = "NeorgUnorderedList5",
                            query = "(unordered_list5_prefix) @icon",
                        },

                        level_6 = {
                            enabled = true,
                            icon = " •",
                            highlight = "NeorgUnorderedList6",
                            query = "(unordered_list6_prefix) @icon",
                        },
                    },

                    marker = {
                        enabled = true,
                        icon = " ❚",
                        highlight = "NeorgMarker",
                        query = "[ (marker_prefix) (link_target_marker) ] @icon",
                    },
                }
            }
        },
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    notes = "~/.config/dev/personal/neorg",
                    private = "~/.config/dev/rsync/neorg"
                },
                index = "index.norg"
            }
        }
    },
}
```

### Actual behavior

When i type `:Neorg gtd views` it throws up error but after i hit enter on error, gtd is working.

### Expected behavior

Get rid of the error when typing `:Neorg gtd views`

### Steps to reproduce

throws up error when doing `:Neorg gtd views`

```
Press ESC to exit without savingError executing vim.schedule lua callback: ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:23: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
        [C]: in function 'sub'
        ...r/start/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:23: in function 'get_node_text'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:1583: in function 'render'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:180: in function 'accumulator'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:135: in function 'recurse_local_nodes'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:138: in function 'recurse_local_nodes'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:141: in function 'func'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:66: in function <...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:55>

```

### Help

No

**Comment by danymat** [comment] 2022-02-27 15:51
Hello, from the error it seems to be a concealer issue, maybe it's not related to gtd.

Are you on latest neorg version + latest TS version ? Can you share to us your tree sitter norg config ?

**Comment by hoaxdream** [comment] 2022-02-28 02:55
> Hello, from the error it seems to be a concealer issue, maybe it's not related to gtd.
> 
> Are you on latest neorg version + latest TS version ? Can you share to us your tree sitter norg config ?

yea probably a concealer issue.

im on the latest neorg + TS, here is my config

```
local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
    return
end

configs.setup {
    ensure_installed = "maintained",
    sync_install = false,
    ignore_install = { "" },
    autopairs = {
        enable = true,
    },
    highlight = {
        enable = true,
        disable = {},
        additional_vim_regex_highlighting = true,
    },
    indent = { enable = true, disable = { "yaml", "lua" } },
    context_commentstring = {
        enable = true,
        enable_autocmd = false,
    },
}
```

**Comment by danymat** [comment] 2022-03-03 13:10
What happens if:

- you disable concealer
- you let concealer enabled, but remove optional configs

**Comment by hoaxdream** [comment] 2022-03-04 23:26
- when i disable concealer everything works.
- if i enable concealer without optional configs it also throws the error

**Comment by danymat** [comment] 2022-03-05 10:45
Okay, then I change the title and re-assign

**Comment by vhyrro** [comment] 2022-03-09 16:29
Wow, this is one difficult thing to debug. I've been looking into this but can't find a fix.

@hoaxdream, does disabling the horizontal line:
```lua
horizontal_line = { enable = false, }
```
Help with anything?

That's my only lead right now lol. I kind of have to take shots in the dark since I can't reproduce the issue on my machine, even with your config.

**Comment by hoaxdream** [comment] 2022-03-09 18:58
hi sir, thanks for your time fixing my problem but i already moved with other note taking plugin. i'll keep watching this great project, specially when it supports for other file format such as markdown. thanks again have a nice day sir.

**Comment by vhyrro** [comment] 2022-03-09 19:07
No worries, I'll keep this issue open though cause I still wanna fix it :P

I'll wait for someone else who potentially might be able to help out in the meantime :)

**Comment by max397574** [comment] 2022-04-18 19:39
@vhyrro is this still not fixed?

**Comment by vhyrro** [comment] 2022-04-19 09:51
I don't know, I haven't been able to reproduce the error on my machine so I have no clue :p

I'll close it for now just to remove the clutter, but if anyone has the issue again then feel free to ping me with a message here

**Closed by vhyrro** 2022-04-19 09:51 UTC
Labels: bug, existing modules
