### ISSUE TITLE
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text

### ISSUE THREAD

**Issue by GaetanLepage** [nvim-neorg/neorg#437] opened 2022-04-27 14:19 UTC
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.8.0-dev

### Neorg setup

```
require 'neorg'.setup {
    load = {
        ["core.defaults"] = {},

        ["core.keybinds"] = {
            config = {
                hook = function(keybinds)
                    keybinds.unmap('norg', 'n', '<C-s>')
                end
            }
        },

        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    notes = "~/notes"
                }
            }
        },

        ["core.norg.concealer"] = { }
    }
}
```

### Actual behavior

There is the following warning: `nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text`

### Expected behavior

No warning

### Steps to reproduce

Open any `.norg` file with the concealer module enabled.

### Other information

https://github.com/nvim-treesitter/nvim-treesitter/commit/c3848e713a8272e524a7eabe9eb0897cf2d6932e

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by vhyrro** [comment] 2022-04-30 15:32
Hey, I've been aware of this for a while now, but unfortunately I'll have to postpone it a little before I get around to fixing it. It seems like an easy task, right? Just replace the usage of `ts_utils.get_node_text()`, but unfortunately it is *much* worse than this.

On a 12.5 thousand LOC codebase, there are many instances where we interchange between `vim.treesitter.get_node_text` and `ts_utils.get_node_text` - usually this is a convenience thing since `ts_utils.get_node_text` returns a table instead of a string. There are many modules that rely on tables being returned, and many modules that rely on strings being returned. I'm gonna have to go through every module and update every one with new logic, so yeah expect it to take a while hah. Sorry if the warning is annoying in the meantime!

I'll probably begin working on a fix on a separate branch in about 2 days' time.

**Comment by vhyrro** [comment] 2022-05-01 18:41
Hey, i believe the warning message should be gone now - mind verifying? :)

**Comment by xfzv** [comment] 2022-05-01 19:36
> Hey, i believe the warning message should be gone now - mind verifying? :)

I'm no longer getting the error after updating to https://github.com/nvim-neorg/neorg/commit/633dfc9f0c3a00a32ee89d4ab826da2eecfe9bd8 but now I'm getting the following error when opening **some** `.norg` files (it seems that it's only occurring with rather large ones):

```lua
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'get_node_text'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:1495: in function 'render'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:205: in function 'accumulator'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:136: in function 'recurse_local_nodes'
        ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:139: in function 'recurse_local_nodes'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:166: in function 'func'
        ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:67: in function <...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:56>
```

**Comment by GaetanLepage** [comment] 2022-05-02 07:20
It works fine on my side: no crash nor warning !

**Comment by max397574** [comment] 2022-05-02 07:29
works for me

**Comment by xfzv** [comment] 2022-05-02 17:32
> ```lua
> Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
> stack traceback:
>         [C]: in function 'error'
>         vim/shared.lua: in function 'validate'
>         vim/shared.lua: in function 'gsplit'
>         vim/shared.lua: in function 'get_node_text'
>         ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:1495: in function 'render'
>         ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:205: in function 'accumulator'
>         ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:136: in function 'recurse_local_nodes'
>         ...ker/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:139: in function 'recurse_local_nodes'
>         ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:166: in function 'func'
>         ...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:67: in function <...t/neorg/lua/neorg/modules/core/norg/concealer/module.lua:56>
> ```

I think I found the culprit, looks like it's the [horizontal lines](https://github.com/nvim-neorg/neorg/blob/main/docs/NFF-0.1-spec.md#horizontal-lines).

To reproduce (with Concealer enabled, of course):

```bash
echo "___" > test.norg
nvim test.norg
```

Also, the error is displayed immediately when typing `___` and exiting insert mode in a new `.norg` file.

**Comment by vhyrro** [comment] 2022-05-04 17:31
Hey @xfzv thanks for the heads up - that one was always a bit buggy. I'll take a look at it later today if I can, although it's unrelated to the current issue. Given that people are saying things work I assume we can close this :)

**Closed by vhyrro** 2022-05-04 17:31 UTC
Labels: bug

**Comment by vhyrro** [comment] 2022-05-04 17:33
> We should maybe leave the issue open until the proper replacement has occurred ?

oops i missed this bit lol. I'd keep it closed for now, i'm actively working on a real fix anyhow, almost done as a matter of fact.

**Comment by max397574** [comment] 2022-06-06 08:26
I opened a pr with a proper replacement now

**Comment by xfzv** [comment] 2022-06-06 17:07
After updating to #475, I'm still getting the warning message:

![image](https://user-images.githubusercontent.com/78810647/172210206-494bd3d5-afb3-4ae0-9f8f-a86bb65f1ac2.png)

**Comment by max397574** [comment] 2022-06-06 17:26
then this isn't from neorg
