### ISSUE TITLE
Exiting `New Note:` prompt causes "Not enough room" error with neovim winbar enabled

### ISSUE THREAD

**Issue by miversen33** [nvim-neorg/neorg#775] opened 2023-03-12 18:59 UTC
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.9.0-dev-1210+g172227a44

### Neorg setup

I am just using what is available on the readme. I suppose 
```lua
{
    load = {
        ["core.defaults"] = {}, -- Loads default behaviour
        ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
        ["core.norg.dirman"] = { -- Manages Neorg workspaces
            config = {
                workspaces = {
                    notes = "/tmp/notes",
                },
            },
        },
     }
}
```

### Actual behavior

The following error is thrown
```
E5108: Error executing lua: BufLeave Autocommands for "<buffer=3>": Vim(append):E36: Not enough room
stack traceback:
        [C]: at 0x5559a2eb8587
```
![Screenshot_20230312_135443](https://user-images.githubusercontent.com/2640668/224566346-502d0390-8129-4310-96bb-e2602929ca8b.png)

Pressing `<Esc>` or `<Enter>` lets you "continue" using neovim, but the floating window stays and shows the top most line of text in it when typing
![Screenshot_20230312_134756](https://user-images.githubusercontent.com/2640668/224565889-4910ee1f-9f76-4cf4-8242-4e97e8c15204.png)

### Expected behavior

The `new note` window to close doing nothing as it does without the winbar being present

### Steps to reproduce

- Open a clean environment (usable lazy config below to reproduce a clean environment)
    EG: `nvim --clean -u mini.lua`
- Wait for lazy to install the dependencies (I used lualine for creating the winbar because I am lazy and don't want to make my own)
- Wait for Neorg to install its tree-sitter parsers
- Close out of the Lazy overlay
- Execute `:Neorg workspace notes`
- Press `,nn`
- Once the `New Note:` Popup is present, press `<Esc>`
- Observe error
- Profit?

```lua
-- Minimal configuration
-- mini.lua
--
-- Auto clear out temp location to ensure fresh download and setup each run
vim.fn.delete('/tmp/lazy.nvim', 'rf')
vim.fn.delete('/tmp/data/lazy.nvim', 'rf')
vim.g.maplocalleader = ','
local lazypath = "/tmp/lazy.nvim/"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local lazyopts = {
    root = "/tmp/data/lazy.nvim"
}

require("lazy").setup({
    {
        "nvim-neorg/neorg",
        build = ":Neorg sync-parsers",
        opts = {
            load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.norg.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "/tmp/notes",
                        },
                    },
                },
            }
        },
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-treesitter/nvim-treesitter"
        },
        config = true
    },
    {
        "nvim-lualine/lualine.nvim", -- Neovim status line
        config = function()
            local lualine = require("lualine")
            lualine.setup({
                winbar = {
                    lualine_a = {'filename'},
                    lualine_b = {},
                    lualine_c = {},
                    lualine_x = {},
                    lualine_y = {},
                    lualine_z = {},
                },
                inactive_winbar = {
                    lualine_a = {},
                    lualine_b = {},
                    lualine_c = {},
                    lualine_x = {},
                    lualine_y = {},
                    lualine_z = {},
                },
            })
        end,
    },
}, lazyopts)
```

### Potentially conflicting plugins

I suppose it is _possible_ that the issue lies with Lualine but I highly doubt it as lualine is just generating a string for neovim to use for the winbar.
It is also _possible_ that this issue comes from Lazy but again, I highly doubt it (and don't feel like removing the idea of a package manager from the equation as it shouldn't be affecting anything here)

### Other information

The error seems to indicate that an issue in the function that is executed on the `BufLeave` event.
A quick bit of sniffing in the code leads me to [this function](https://github.com/nvim-neorg/neorg/blob/9766bef893ec993af9408ea0d44a8f13adbd1e80/lua/neorg/modules/core/ui/module.lua#L79-L94)
which I would guess is the culprit though its relatively simple. I don't really know _why_ this would cause an issue but other floating window plugins have no issue with the winbar being present.

That's really all I got here :/

### Help

No

**Comment by d-r-a-b** [comment] 2023-04-20 16:18
I confirm reproduction, but it seems like it may be a lualine winbar thing.

I say this because if I get rid of the lualine block and just set winbar to a string, I no longer reproduce and `<Esc><Esc>` exits the new note dialog without causing any error or retained window.

``` lua
-- Minimal configuration
-- mini.lua
--
-- Auto clear out temp location to ensure fresh download and setup each run
vim.fn.delete('/tmp/lazy.nvim', 'rf')
vim.fn.delete('/tmp/data/lazy.nvim', 'rf')
vim.g.maplocalleader = ','
local lazypath = "/tmp/lazy.nvim/"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local lazyopts = {
    root = "/tmp/data/lazy.nvim"
}

require("lazy").setup({
    {
        "nvim-neorg/neorg",
        build = ":Neorg sync-parsers",
        opts = {
            load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "/tmp/notes",
                        },
                    },
                },
            }
        },
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-treesitter/nvim-treesitter"
        },
        config = function(_,opts)
            require('neorg').setup(opts)
            vim.opt.winbar="%n %t"
        end,
    },
}, lazyopts)

```

Note: you do have to `mkdir /tmp/notes`.

**Comment by vhyrro** [comment] 2023-04-27 17:23
Yeah it's likely this is a lualine problem. I can't reproduce with a simple, plain winbar. Maybe I can track down the exact source.

**Comment by vhyrro** [comment] 2023-04-27 17:29
Update: I can't seem to track down the exact source :laugh:. I'll leave this issue open until I (or someone) figures out if there's anything Neorg can do to mitigate the lualine error (without being too hacky).

**Comment by xfo-0** [comment] 2023-04-27 17:35
I believe it is an upstream issue as mentioned here `https://github.com/neovim/neovim/issues/19464`

**Comment by vhyrro** [comment] 2023-04-27 17:43
Aha, thanks for pointing me to that! There may actually be a way to fix this as a temporary workaround in neorg's case, as the popup only uses the *Leave autocommands, which allows us to clear the winbar before any errors occur. Time to test it.

**Comment by vhyrro** [comment] 2023-04-27 17:45
Okay, I just pushed a commit on the latest main branch that attempts to fix this. Could anyone with lualine try it out real quick please? cc @d-r-a-b @miversen33

**Comment by xfo-0** [comment] 2023-04-27 17:51
It seems that the issue is still present

**Comment by vhyrro** [comment] 2024-06-11 19:07
Forgot to close this as "unfixable from our end". Will do that now :)

**Closed by vhyrro** 2024-06-11 19:07 UTC
Labels: bug
