### ISSUE TITLE
No news command

### ISSUE THREAD

**Issue by edshamis** [nvim-neorg/neorg#801] opened 2023-04-15 10:25 UTC
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.10.0-dev-75+gc2e47e7be

### Neorg setup

  {
    "nvim-neorg/neorg",
    build = ":Neorg sync-parsers",
    opts = {
      load = {
        ["core.defaults"] = {}, -- Loads default behaviour
        ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
        ["core.norg.dirman"] = { -- Manages Neorg workspaces
          config = {
            workspaces = {
              notes = "~/notes",
            },
          },
        },
        ["core.norg.news"] = { config = { check_news = true } },
      },
    },
    dependencies = { { "nvim-lua/plenary.nvim" } },
  },

### Actual behavior

Running command `:Neorg news all` yields this error
```
...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:231
Error when executing `:Neorg news` - such a command does not exist!
```

### Expected behavior

Well, it's my first experience with Neorg, but I'd expect to see some news 

### Steps to reproduce

:Neorg news all

### Help

None

**Comment by d-r-a-b** [comment] 2023-04-15 11:59
I don't reproduce. Please try to give a full minimal config when you file a bug report, it makes it much easier to actually track anything down. See below for a fleshed out example where I took your block and put it into a minimal config, tested it, and could not reproduce the behavior you described.

<details>
<summary>minimal_init.lua</summary>

```lua
vim.cmd.colorscheme "peachpuff"
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)
require('lazy').setup({
    {
        "nvim-neorg/neorg",
        build = ":Neorg sync-parsers",
        opts = {
            load = {
                ["core.defaults"] = {}, -- Loads default behaviour
                ["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
                ["core.norg.dirman"] = { -- Manages Neorg workspaces
                    config = {
                        workspaces = {
                            notes = "~/notes",
                        },
                    },
                },
                ["core.norg.news"] = { config = { check_news = true } },
            },
        },
        dependencies = { { "nvim-lua/plenary.nvim" }, {"nvim-treesitter/nvim-treesitter"}},
    },
})
```
</details>

1. Expand the above `minimal_init.lua` and save it somewhere
2. `nvim -u minimal_init.lua`. You should get a nice blank buffer that is bright peach to let you know you loaded this minimal config (colorscheme peachpuff)
3. `:Neorg news all` and you should get news.
4. `zO` to open all the folds.

**Comment by Aumnescio** [comment] 2023-04-20 09:27
News disappeared for me too after updating to latest Neorg version. Tested the minimal config above too.  Same error.

Even after deleting the plugin and reinstalling, I have no news.

**Comment by Aumnescio** [comment] 2023-04-20 09:48
I suspect I fixed it after deleting and regenerating `neorg.mpack` in `~/.local/share/nvim/`.

I got the `neorg.mpack` file back by calling `:Neorg workspace` after the full reinstall of Neorg.

There was some reference to `core.norg.news` and such in there. Now its correctly `core.news`.

**Comment by d-r-a-b** [comment] 2023-04-20 14:54
Yeah, the config above was written before the refactor of `core.norg.* -> core.*`, glad you were able to still make it work by `s/core.norg/core/` 😁

Not having news isn't the same as the news command not working, which is what the original bug report is reporting.
> ...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:231
> Error when executing `:Neorg news` - such a command does not exist!

@edshamis when you say that you "Did it, still no news 😭", are you still receiving an error?

Wanting the news files to be updated is a separate issue -- file it separately if it is a strong concern, but you can also click on the tags in the GH repo to see what changes happened with each release since Nov 2022 or look at #announcements in the discord.

As a community member, I agree that it would be nicer if the news files got updated, but at least there are other options to find the information you want. Again, I am not a dev, my views do not reflect those of the project, but I am just trying to help out a project I like by cleaning up these types of GH issues so that the devs can focus their efforts on bugfixes/functionality.

**Comment by d-r-a-b** [comment] 2023-04-20 19:21
Weird, assuming you saw the pink screen from `colorscheme peachpuff` it should work fine since I gave the whole config. Just to be sure, you used the config on its own, right? Not just copy/pasted it into your larger config?

For `:Neorg workspace` are you sure you got the same error? I would be concerned if neorg was saying `Error when executing :Neorg news - such a command does not exist!` when you didn't call `:Neorg news`. Other people have gotten tripped up on not doing a `mkdir ~/notes` first.

I hope things work out for you, but if you do decide that this issue doesn't matter to you, can you close it?

**Comment by Aumnescio** [comment] 2023-04-20 20:39
Hes replying to my fix. But the `neorg.mpack` is located higher in the directory structure, so you did not delete it. It's literally at `~/.local/share/nvim/neorg.mpack`, not under the lazy or neorg folders.

He isn't saying that the workspace command itself is erroring.

**Comment by vhyrro** [comment] 2023-04-27 17:17
Oh, I absolutely overlooked this. The cache is out of date with the news module because of the naming change, damn.

The only way to fix this is honestly awkward and hacky, and just leaves legacy code laying around (i.e. you also have to check for the existence of an old `core.norg.news` key).

In general, I'm inclined to soon remove the news module. It doesn't serve much of a purpose anymore unfortunately. I'm definitely not bothered to write the news :p, so I'd much rather something along the lines of `:h neorg-news` with only breaking changes instead, or just people viewing the commit changelog/CHANGELOG.md which is fairly easy to follow anyway. I don't expect many more syntax changes since `1.0` has been hit, which was my main motivation for the news module.

To top it all off, the bugginess of trying to maintain a cache on the filesystem in sync with data pulled in via git is a hassle, so it'd be one less unstable thing in the codebase :sweat_smile:

**Closed as not planned** 2023-04-28 09:30 UTC
Labels: bug
