### ISSUE TITLE
:help neorg raises a bunch of errors!

### ISSUE THREAD

**Issue by josephsdavid** [nvim-neorg/neorg#249] opened 2021-12-15 14:57 UTC
### Prerequisites

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)
- [X] I am using the latest version of the plugin
- [X] I am using either 0.6 stable or the latest compiled neovim version

### Neovim Version

NVIM v0.7.0-dev+719-gbdfea9d9a

### Neorg setup

```lua
    require('neorg').setup {
        -- Tell Neorg what modules to load
        load = {
            ["core.defaults"] = {}, -- Load all the default modules
            ["core.norg.completion"] = { config = { engine = "nvim-cmp" } } ,-- We current support nvim-compe and nvim-cmp only
            ["core.norg.concealer"] = {}, -- Allows for use of icons
            ["core.keybinds"] = { -- Configure core.keybinds
                config = {
                    default_keybinds = true, -- Generate the default keybinds
                    neorg_leader = "<Leader>o" -- This is the default if unspecified
                }
            },

            ["core.norg.dirman"] = { -- Manage your directories with Neorg
                config = {
                    workspaces = {
                        my_workspace = "~/neorg",
                        notes = "~/notes",
                        chess = "~/chess",
                        workflow = "~/work/workflow/src/",
                        structures = "~/data-structures",
                        work = "~/work/"

                    },
            autodetect = true,
                }
            },

        },
    }
```

### Actual behavior

:help neorg raises the following error: 
```:help neorg         Error detected while processing BufEnter Autocommands for "*.norg":
E5108: Error executing lua ...d/neorg/lua/neorg/modules/core/norg/concealer/module.lua:1445: attempt to index field 'quote' (a nil value)
stack traceback:
        ...d/neorg/lua/neorg/modules/core/norg/concealer/module.lua:1445: in function 'render'
        ...d/neorg/lua/neorg/modules/core/norg/concealer/module.lua:300: in function 'trigger_icons'
        ...d/neorg/lua/neorg/modules/core/norg/concealer/module.lua:2081: in function 'on_event'
        /home/david/.data/plugged/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
        ...ged/neorg/lua/neorg/modules/core/autocommands/module.lua:47: in function '_neorg_module_autocommand_triggered'
        [string ":lua"]:1: in main chunk
```
This error also happens when switching from a current buffer to the help window (for example say I have notes.norg on top and :help neorg-data-tags):
* if I hit `<C-w><C-k>` to go from help to notes, no problem
* if I hit `<C-w><C-j>` to go back, error message

Other commands which raise the same error:
* :help neorg-links
* :help neorg-markers
* :help neorg-name-tag
* :help neorg-foreplay raises a different error: E434: Can't find tag pattern
* :help neorg-insertions
* :help neorg-ordered-tag
* :help neorg-basic-markup
* :help neorg-continuation
* :help neorg-advanced-markup
* :help neorg-indentation-reversal

### Expected behavior

:help neorg does not raise error messages

### Steps to reproduce

neorg: main branch, commit: 3eef519b3fc3622983870f6e3ea724192f663e77

### Potentially conflicting plugins

none

### Other information

does not show up in norg logs

### Help

No

### Implementation help

I would like to help in some ways, but this is my first experience with lua!

**Comment by max397574** [comment] 2021-12-15 15:06
This is an issue we just discovered some minutes ago (don't know about `:help neorg-foreplay raises a different error: E434: Can't find tag pattern` though)
The other error occurs when there are quotes with nesting level 3 or more. There are quotes like this in the helpfiles.

**Comment by max397574** [comment] 2021-12-15 16:03
you can keep it open so there's an open issue for this problem

**Comment by vhyrro** [comment] 2021-12-15 16:31
Hey! I think I managed to fix this, could you update Neorg and verify that for me? Try out a few help pages and see whether they function as intended. If all works then we can close this issue :D

**Comment by josephsdavid** [comment] 2021-12-15 16:35
sounds good!

**Comment by josephsdavid** [comment] 2021-12-15 16:37
Looks like we are good, no issues with any help commands or window changing, nice work!

**Closed** 2021-12-15 16:37 UTC
Labels: bug
