### ISSUE TITLE
core.promo: whitespace on empty lines

### ISSUE THREAD

**Issue by YohananDiamond** [nvim-neorg/neorg#852] opened 2023-05-06 22:31 UTC
Hello! I was going to file this under the bug report template but it doesn't seem to be necessarily a bug.
Basically: when indenting something (forwards or backwards) with `core.promo` enabled, previously empty lines are prefixed with whitespace.

Before `>>`:
![image](https://user-images.githubusercontent.com/23298480/236648895-3bccd828-e53f-4259-b33c-4bb14cd8cb5f.png)

After `>>` (pay attention to line 03):
![image](https://user-images.githubusercontent.com/23298480/236648919-6bd33f27-2197-454e-9fe4-8001f1350f64.png)

I'm not sure whether to call this a bug or just something I don't quite like, but I've noticed that, as an example, `doc/neorg.norg` doesn't have these spaces on empty "indented" lines.

**Comment by d-r-a-b** [comment] 2023-05-10 23:32
Just a community member working through the GH issues. Agree this reproduces on my end as of current HEAD which is cc2834ae2beb2d5baa75d15848a94dae022faa2c. It's not really a bug, as you say, since technically per spec the whitespace is semantically meaningless here. For the moment, I've found that mitigating with a plugin like Mini.TrailSpaces or trim.nvim works well enough.

There's been a brief surge of activity in concealer contribution thanks to a very nice contributor, if you feel like you are up to helping out and taking this on in the form of a PR, the place to look would probably be in https://github.com/nvim-neorg/neorg/tree/main/lua/neorg/modules/core/concealer. There was a recent promo refactor as well, so it should be comparatively easy to reference that refactor to figure out what bits of code are involved.

**Comment by vhyrro** [comment] 2023-05-15 16:19
Hey, this should now be fixed in the latest `main`! If there are still problems then feel free to reopen :)

**Closed by vhyrro** 2023-05-15 16:19 UTC

**Comment by YohananDiamond** [comment] 2023-05-16 04:06
All good over here! Thanks for the help.
