### ISSUE TITLE
anchor definition not concealed when conceallevel=2

### ISSUE THREAD

**Issue by champignoom** [nvim-neorg/neorg#838] opened 2023-05-04 11:25 UTC
### Prerequisites

- [X] I am using the latest stable release of Neovim
- [X] I am using the latest version of the plugin

### Neovim Version

v0.9.0

### Neorg setup

```lua
require('neorg').setup {
	load = {
		["core.defaults"] = {}, -- Loads default behaviour
		["core.norg.concealer"] = {}, -- Adds pretty icons to your documents
		["core.norg.dirman"] = { -- Manages Neorg workspaces
			config = {
				workspaces = {
					notes = "~/notes",
				},
			},
		},
	},
}
```

### Actual behavior

It becomes:
```
{* heading}
```

### Expected behavior

It should remain:
```
{◉ heading}
```

### Steps to reproduce

test.norg:
```
{* heading}
```
By entering normal mode, it's concealed to
```
{◉ heading}
```

Now `:set conceallevel=2`

### Help

Yes

**Comment by champignoom** [comment] 2023-05-05 08:34
Ok I just found out that "no-conceal" might be intended for link targets:

https://github.com/nvim-neorg/neorg/blob/6aa9fd303c807ed1ca3fb15cdeab1e322d02fd31/lua/neorg/modules/core/concealer/module.lua#L1103

But then the problem becomes that it does get concealed when conceallevel != 2. The `and has_conceal` part below looks suspicious.

https://github.com/nvim-neorg/neorg/blob/6aa9fd303c807ed1ca3fb15cdeab1e322d02fd31/lua/neorg/modules/core/concealer/module.lua#L118-L122

**Comment by vhyrro** [comment] 2023-05-05 15:07
This is intended, when vim's concealing is enabled then there's no way to place the extmark, otherwise the icon overlays the concealed text, which looks like this: `◉eading`. There's no way we can implement "reconcealing" on every cursor move, otherwise the entire Neovim instance would very quickly slow down to a crawl.

When you don't hide the text, the concealer will display the icon, as it knows it will never break anything. Otherwise, it just doesn't bother rendering at all.

Closing since this is intended behaviour :)

**Closed by vhyrro** 2023-05-05 15:07 UTC
Labels: bug

**Comment by champignoom** [comment] 2023-05-19 14:54
This is now fixable with https://github.com/nvim-neorg/neorg/pull/834.

**Comment by champignoom** [comment] 2023-05-21 20:36
but the fix might trigger a neovim bug https://github.com/neovim/neovim/issues/23706
