### ISSUE TITLE
Shifting blocks of text using [COUNT]<< and [COUNT]>> Stopped working

### ISSUE THREAD

**Issue by KiLLeRRaT851** [nvim-neorg/neorg#657] opened 2022-11-10 22:56 UTC
### Prerequisites

- [X] I am using either 0.7 stable with the `0.0.12` tag or the latest compiled Neovim version
- [X] I am using the latest version of the plugin

### Neovim Version

NVIM v0.8.0

### Neorg setup

```
require('neorg').setup {
		load = {
				["core.defaults"] = {},
				["core.integrations.telescope"] = {},
				["core.norg.dirman"] = {
						config = {
								workspaces = {
										work = "~/GBox/Notes/neorg/work"
										-- home = "~/notes/home",
								}
						}
				},
				["core.norg.concealer"] = {
					 config = {}
				},
				["core.gtd.base"] = { -- https://github.com/nvim-neorg/neorg/wiki/Getting-Things-Done
					 config = {
						workspace = "work"
					 }
				},
				["core.norg.completion"] = { -- https://github.com/nvim-neorg/neorg/wiki/Completion
					config = {
						engine = "nvim-cmp"
				},
				-- NOT SURE IF I NEED THE BELOW WITH THE ABOVE CONFIGURED?
				["core.integrations.nvim-cmp"] = { -- https://github.com/nvim-neorg/neorg/wiki/Nvim-Cmp
					 config = {}
				},
				["core.norg.dirman"] = { -- https://github.com/nvim-neorg/neorg/wiki/Dirman
					config = {
						workspaces = {
							work = "~/GBox/Notes/neorg/work", -- Format: <name_of_workspace> = <path_to_workspace_root>
							-- my_other_notes = "~/work/notes",
						},
						autochdir = true, -- Automatically change the directory to the current workspace's root every time
						index = "index.norg", -- The name of the main (root) .norg file
					}
				},
				-- ["core.keybinds"] = { -- https://github.com/nvim-neorg/neorg/wiki/User-Keybinds
				-- 		config = {
				-- 				default_keybinds = false,
				-- 		}
				-- }
			}
		}
}

```

### Actual behavior

When I have a paragraph, or a few lines that I want to shift left or right using `[count]<<` or `[count]>>` it only indents the first line.

```
  @code bash <-- CURSOR HERE ON THIS LINE, IN NORMAL MODE, ENTER 5>> to SHIFT 5 LINES TO HTE RIGHT, only this line gets moved.
    [General]
    HaltCommand=
    InputMethod=
    RebootCommand=
  @end
```

### Expected behavior

All the lines specified with `COUNT` should be shifted left/right

### Steps to reproduce

See above.

### Other information

I spoke to @max397574 on discord, and this is what he mentioned:

> that's because we did sth with the >> (and <<) so you can use it on headings, quotes, lists etc to change the level of them
seems like the fallback isn't working correctly
open an issue in the repo

**Comment by vhyrro** [comment] 2022-11-12 18:16
Hey! I have partially fixed this in the latest commit. If you do `5>>` on regular text it should work as intended now! It still won't work for special text objects like headings but I ran out of time today :p

I'll close this when I fully fix the problem.

**Comment by KiLLeRRaT851** [comment] 2022-11-13 21:33
Excellent, thanks for taking a look.  Looking forward to getting it sorted fully :)

**Comment by vhyrro** [comment] 2023-04-29 16:36
Has been fixed fully as of the rewrite found [here](https://github.com/nvim-neorg/neorg/pull/817)!

**Closed by vhyrro** 2023-04-29 16:36 UTC
Labels: bug
